import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex justify-between p-2 bg-red-500 text-white">
            <h1>Maxime Prévot</h1>
            <h2>MMI</h2>
          </nav>
        </header>
        {children}
        </body>
    </html>
  );
}
